version: '3'

services:

  harena-space:
    # image: datasci4health/harena-space
    build: ./
    ports:
      - "10010:10010"
    environment:
      - ENV_SILENT=true            
      - HOST=0.0.0.0
      - PORT=10010
      - NODE_ENV=production
      - APP_NAME=harena-space
      - APP_URL=http://0.0.0.0:10010
      - CACHE_VIEWS=false
      - APP_KEY=Xw8Ctu827gw290qDx4GSnUlyTY3a6x
      - HASH_DRIVER=bcrypt
      - HARENA_SPACE_URL=http://localhost:10010
      - HARENA_SPACE_API_VERSION=v1
      - HARENA_MANAGER_URL=http://localhost:10020
      - HARENA_MANAGER_API_VERSION=v1
      - HARENA_LOGGER_URL=http://localhost:10030
      - HARENA_LOGGER_API_VERSION=v1        
    restart: always
    networks:
      - harena-space

networks:
  harena-space:
    driver: bridge
