version: '3'

services:

  harena-space:
    container_name: harena-space
    image: faguim:harena-space:latest
    ports:
      - "10010:10010"
    environment:
      - ENV_SILENT=false
      - HOST=0.0.0.0
      - PORT=10010
      - NODE_ENV=debug
      - APP_NAME=harena-space
      - APP_URL=http://0.0.0.0:10010
      - CACHE_VIEWS=false
      - APP_KEY=Xw8Ctu827gw290qDx4GSnUlyTY3a6x
      - HASH_DRIVER=bcrypt
      - HARENA_SPACE_URL=http://localhost:10010
      - HARENA_SPACE_API_VERSION=v1
      - HARENA_MANAGER_URL=http://localhost:10020
      - HARENA_MANAGER_API_VERSION=v1
      - HARENA_LOGGER_URL=http://localhost:10030
      - HARENA_LOGGER_API_VERSION=v1
      - MANAGER_HOST=manager
    depends_on:
      - harena-manager
    restart: always
    networks:
      - harena-space

  harena-manager:
    image: faguim:harena-manager:latest
    container_name: harena-manager
    ports:
      - "10020:10020"
    environment:
      - ENV_SILENT=false
      - HOST=0.0.0.0
      - PORT=10020
      - NODE_ENV=dev
      - APP_NAME=harena-manager
      - APP_URL=http://0.0.0.0:10020
      - CACHE_VIEWS=false
      - APP_KEY=sHuh8734nANKdmasdk31345Kasd
      - DB_CONNECTION=mysql
      - DB_HOST=harena-manager-database
      - DB_PORT=3306
      - DB_DATABASE=harena-manager
      - DB_USER=jacinto
      - DB_PASSWORD=jacinto
      - HASH_DRIVER=bcrypt
    depends_on:
      - harena-manager-database
    restart: always
    networks:
      - harena-space

  harena-manager-database:
    image: mysql:5.7
    ports:
      - "10021:3306"
    volumes:
      - harena-manager-database:/var/lib/mysql
    environment:                                # will be  replaced to .env vars, as in ${DB_PASSWORD}
      - MYSQL_DATABASE=harena-manager
      - MYSQL_USER=jacinto
      - MYSQL_PASSWORD=jacinto
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    networks:
      - harena-space

  harena-manager-database-ui:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 10022:80
    environment:
      - PMA_ARBITRARY=0                         # connection to any server
      - PMA_HOST=harena-manager-database
      - PMA_PORT=3306
    depends_on:
      - harena-manager-database
    networks:
      - harena-space

volumes:
  harena-manager-database:
    driver: "local"

networks:
  harena-space:
    driver: bridge
